version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    networks:
      - rabbitmq_go_net
  scrimfinderapi:
    container_name: "scrimFinder-API"
    build:
      dockerfile: Dockerfile
      context: ../scrimFinder-API
    ports:
      - 8082:8082
    networks:
      - spring-cloud-network
  scrimfinderwq:
    depends_on:
      - rabbitmq
    container_name: "scrimFinder-WQ"
    build:
      dockerfile: Dockerfile
      context: ../scrimfinder-WQ
    ports:
      - 8081:8081
  scrimfinderfe:
    container_name: "scrimFinder-FE"
    build:
      dockerfile: Dockerfile
      context: ../scrimFinder-FE
    ports:
      - 8080:8080
networks:
  rabbitmq_go_net:
    driver: bridge
  spring-cloud-network:
    driver: bridge